services:
  - type: web
    name: classroom-notes-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn projectname.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projectname.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
